apiVersion: v1
kind: Service
metadata:
  name: grpc-hello
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.66.203
  selector:
    app: grpc-hello
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
